version: '3.7'

services:
  todo:
    build:
      context: .
      target: development
    command: npx nodemon server.js
    depends_on:
      - postgres
    environment:
      PORT: 8080
    ports:
      - '3000:8080'
    volumes:
      - ./backend:/srv/todo/backend
      - todo_backend_node_modules:/srv/todo/backend/node_modules

  postgres:
    image: postgres:12

volumes:
  todo_backend_node_modules:
